./build.gradle:
  flag: //Yeoman:libs
  text: |-
    compile 'org.neo4j:neo4j-ogm-core:2.0.4'
    compile 'org.neo4j:neo4j-ogm-http-driver:2.0.4'
    compile 'org.neo4j:neo4j-ogm-embedded-driver:2.0.4'
    compile 'org.neo4j:neo4j-ogm-bolt-driver:2.0.4'

