os:
  - linux
  - osx

language: node_js
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; export CC=gcc-4.8; fi
  - npm install

cache:
  directories:
    - node_modules