#Site
site_name: generator-generator2
site_description: New yeoman generator with easier and opinionated workflow.
site_author: Uroš Jarc
site_url: http://urosjarc.github.io/generator-generator2
site_favicon: media/favicon.ico
site_dir: build/docs

#Repo
repo_url: https://github.com/urosjarc/generator-generator2

#Copyright
copyright: Copyright © 2016 Uroš Jarc

#Documentation and theme
theme: material
docs_dir: docs

#Page tree
pages:
 - 'Home': index.md
 - 'Contribution': contribution.md
 - 'Documentation': documentation.md
 - 'Changes': changes.md

#Theme specific
extra:
  version: 0.0.0
  logo: media/logo.png
  github:
    download_release: true
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'urosjarc'
    twitter: 'urosjarc'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Google Analytics
google_analytics:
  - 'UA-53923399-3'
  - 'auto'
