site_name: generator-generator2
site_description: Yeoman 2nth generator with easier and opinionated workflow.
site_author: Uroš Jarc
site_url: 'http://urosjarc.github.io/generator-generator2'
site_favicon: media/favicon.ico
site_dir: build/docs
repo_url: 'https://github.com/urosjarc/generator-generator2'
copyright: Copyright © 2016 Uroš Jarc
theme: material
docs_dir: docs
pages:
  - Project: index.md
  - Tutorial: tutorial.md
  - Contribution: contribution.md
  - Documentation: documentation.md
  - Changes: changes.md
extra:
  version: 0.0.1
  logo: media/logo.png
  github:
    download_release: true
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  author:
    github: urosjarc
    twitter: urosjarc
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
google_analytics:
  - UA-53923399-3
  - auto
extra_css:
  - /template/theme.css
  - /template/fadein.css
