site_name: generator-generator2
site_url: https://github.com/urosjarc/generator-generator2
repo_url: https://github.com/urosjarc/generator-generator2
site_description: New yeoman generator with easier and opinionated workflow.
site_author: Uroš Jarc
site_favicon: media/favicon.ico
copyright: Copyright © 2016 Uroš Jarc

theme: mkdocs #readthedocs
docs_dir: docs
site_dir: build/mkdocs

pages:
 - 'Home': index.md
 - 'Contribution': contribution.md
 - 'Documentation': documentation.md
 - 'Changes': changes.md
