site_name: <%-app.name%>
site_description: <%-app.description%>
site_author: <%-app.authorName%>
site_url: '<%-app.homepage%>'
site_favicon: media/favicon.ico
site_dir: build/docs
repo_url: '<%-app.repoUrl%>'
copyright: Copyright © <%-new Date().getFullYear()%> <%-app.authorName%>
theme: material
docs_dir: docs
pages:
  - Project: index.md
  - Tutorial: tutorial.md
  - Contribution: contribution.md
  - Developers: developers.md
  - Documentation: documentation.md
  - Changelog: changelog.md
extra:
  version: 0.0.0
  logo: media/logo.png
  github:
    download_release: true
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  author:
    github: <%-app.githubUser%>
<%if (app.twitterUser) { -%>
    twitter: <%-app.twitterUser%>
<% } -%>
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
google_analytics:
  - UA-53923399-3 #Todo: Add google analytics!
  - auto
extra_css:
  - /template/theme.css
  - /template/fadein.css
